package com.nikospavlopoulos.skydivingrest.mapper;

import com.nikospavlopoulos.skydivingrest.dto.UserInsertDTO;
import com.nikospavlopoulos.skydivingrest.dto.lookup.UserLookupDTO;
import com.nikospavlopoulos.skydivingrest.model.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.data.domain.Page;

@Mapper (componentModel = "spring")
public interface UserMapper {

    // Mapping user to UserLookupDTO
    UserLookupDTO userToUserLookupDTO(User user);

    // Mapping user lists to UserLookupDTO
    default Page<UserLookupDTO> userListToUserLookupDTO(Page<User> users) {
        return users.map(this::userToUserLookupDTO);
    };

    // Mapping UserInsertDTO to User
    // Ignoring the autogenerated and default ones
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "uuid", ignore = true)
    @Mapping(target = "active", ignore = true)
    @Mapping(target = "role", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    User userInsertDTOtoUser(UserInsertDTO dto);


}
