name: SkydiveREST Tests

on:
  push:
    branches: ["docker", "main"]
  pull_request:
    branches: ["docker", "main"]

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java 21

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # 3. Cache Gradle dependencies and wrapper
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle*', '**/settings.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Run tests only
      - name: Run tests
        run: ./gradlew test --no-build-cache --continue

      # 5. Upload test result XML files
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: build/test-results/test

      # 6. Upload test report HTML files
      - name: Upload test HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: build/reports/tests/test

      # 7 Upload JaCoCo HTML report
      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/jacocoHtml

      # 7 Upload JaCoCo XML report
      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

